### GET request to example server
PUT http://localhost:8080/users
Content-Type: application/json

{
    "email": "test@test.ru",
    "login": "test_login",
    "user_name": "test",
    "birthday": "2017-01-09"
}
###