CREATE TABLE IF NOT EXISTS filmorate.users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(250) NOT NULL,
    login VARCHAR(50) NOT NULL,
    user_name VARCHAR(50),
    birthday DATE,
    CONSTRAINT unique_email UNIQUE (email),
    CONSTRAINT unique_login UNIQUE (login),
    CONSTRAINT unique_username UNIQUE (user_name)
);

CREATE TABLE IF NOT EXISTS filmorate.films (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name VARCHAR(50) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS filmorate.genre(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25) NOT NULL,
    CONSTRAINT unique_genre_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS filmorate.mpa_rating(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name VARCHAR(25),
    CONSTRAINT check_valid_mpa_rating CHECK (rating_name IN ('G', 'PG', 'PG_13', 'R', 'NC_17'))
);

CREATE TABLE IF NOT EXISTS filmorate.film_genre(
    film_id INTEGER REFERENCES filmorate.films(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES filmorate.genre(id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS filmorate.film_mpa_rating(
    film_id INTEGER NOT NULL,
    film_mparating INTEGER NOT NULL,
    CONSTRAINT fk_film_id FOREIGN KEY (film_id) REFERENCES filmorate.films(id) ON DELETE CASCADE,
    CONSTRAINT fk_mparating_id FOREIGN KEY (film_mparating) REFERENCES filmorate.mpa_rating(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, film_mparating)
);

CREATE TABLE IF NOT EXISTS filmorate.users_films_likes(
    film_id INTEGER,
    user_id INTEGER,
    CONSTRAINT fk_likes_film FOREIGN KEY (film_id) REFERENCES filmorate.films(id) ON DELETE CASCADE,
    CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES filmorate.users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS filmorate.friendships(
    user_id INTEGER REFERENCES filmorate.users(id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES filmorate.users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    request_date DATE NOT NULL,
    accepted_date DATE,
    CONSTRAINT check_status CHECK (status IN ('CONFIRMED', 'NOT_CONFIRMED'))
)